all:
	$ ml-lex Boolean.lex
	$ ml-yacc Boolean.yacc 
	$ mlton a2.mlb

.PHONY:clean
clean:
	$(RM) Boolean.lex.sml
	$(RM) Boolean.yacc.sig
	$(RM) Boolean.yacc.sml
	$(RM) Boolean.yacc.desc
	$(RM) a2
        	 
